# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true
mathjax: false

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Links
links:
  Weibo: http://weibo.com/123238305

# Miscellaneous
google_analytics:
favicon:
twitter:
google_plus:
fb_admins: 
fb_app_id:


# Baidu share
baidushare: false

baidu_tongji: true